name = "tokengating-cart-checkout-validation-example"
type = "cart_checkout_validation"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/tokengating-cart-checkout-validation-example.wasm"

[ui.paths]
create = "/"
details = "/"
